// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
// Step 2: /onboarding/name, /routines/add 경로 추가 (granite dev 자동 생성 경로)
// Step 4: /check 경로 추가 (딥링크: intoss://eomma-yak-meokja/check?routineId={id})
// Step 6: /badges, /calendar 경로 추가 (스트릭 + 배지 컬렉션)
// Step 8a: /family/share, /family/connect, /family/dashboard 경로 추가 (페어링·케어러)
import { Route as _IndexRoute } from 'pages/index';
import { Route as _OnboardingNameRoute } from 'pages/onboarding/name';
import { Route as _RoutinesAddRoute } from 'pages/routines/add';
import { Route as _RoutinesListRoute } from 'pages/routines/list';
import { Route as _CheckRoute } from 'pages/check/[routineId]';
import { Route as _BadgesRoute } from 'pages/badges/index';
import { Route as _CalendarRoute } from 'pages/calendar/index';
import { Route as _FamilyShareRoute } from 'pages/family/share';
import { Route as _FamilyConnectRoute } from 'pages/family/connect';
import { Route as _FamilyDashboardRoute } from 'pages/family/dashboard';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/': (typeof _IndexRoute)['_inputType'];
    '/onboarding/name': (typeof _OnboardingNameRoute)['_inputType'];
    '/routines/add': (typeof _RoutinesAddRoute)['_inputType'];
    '/routines/list': (typeof _RoutinesListRoute)['_inputType'];
    '/check': (typeof _CheckRoute)['_inputType'];
    '/badges': (typeof _BadgesRoute)['_inputType'];
    '/calendar': (typeof _CalendarRoute)['_inputType'];
    '/family/share': (typeof _FamilyShareRoute)['_inputType'];
    '/family/connect': (typeof _FamilyConnectRoute)['_inputType'];
    '/family/dashboard': (typeof _FamilyDashboardRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/': (typeof _IndexRoute)['_outputType'];
    '/onboarding/name': (typeof _OnboardingNameRoute)['_outputType'];
    '/routines/add': (typeof _RoutinesAddRoute)['_outputType'];
    '/routines/list': (typeof _RoutinesListRoute)['_outputType'];
    '/check': (typeof _CheckRoute)['_outputType'];
    '/badges': (typeof _BadgesRoute)['_outputType'];
    '/calendar': (typeof _CalendarRoute)['_outputType'];
    '/family/share': (typeof _FamilyShareRoute)['_outputType'];
    '/family/connect': (typeof _FamilyConnectRoute)['_outputType'];
    '/family/dashboard': (typeof _FamilyDashboardRoute)['_outputType'];
  }
}
